theme: jekyll-theme-modernist
title: LGBTQ+ and Friends Meetup Homepage
description: A weekly meet up that offers support, encouragement, and love from all corners of the world.
url: https://vrlgbtqmeetup.github.io/